---
- name: Provision and Manage EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: my_aws             # Key used for SSH
    region: us-east-1            # Region may affect response and pricing
    image: ami-0583d8c7a9c35822c  # Amazon or AMI of manually launched instances
    instance_type: t2.micro       # Choose instance type, check AWS for pricing
    sec_group: "test-security-group"

  tasks:
    - name: Provisioning EC2 instances
      block:
        - name: Create security group
          amazon.aws.ec2_security_group:
            name: "{{ sec_group }}"
            description: "Sec group for app"
            region: "{{ region }}"
            rules:
              - proto: tcp
                ports:
                  - 22
                cidr_ip: 0.0.0.0/0
                rule_desc: allow all on ssh port

        - name: Create Key Pair
          amazon.aws.ec2_key:
            name: "{{ key_name }}"
            region: "{{ region }}"
            key_material: "{{ lookup('file', './my_aws.pub') }}"

        - name: Start an EC2 instance with a public IP address
          amazon.aws.ec2_instance:
            name: "public-compute-instance"
            key_name: "{{ key_name }}"
            instance_type: "{{ instance_type }}"
            security_group: "{{ sec_group }}"
            region: "{{ region }}"
            network:
              assign_public_ip: true
            image_id: "{{ image }}"
            tags:
              Environment: Testing
          register: ec2_result

      tags: ['create_ec2']

    - name: Retrieve and Display Instance Facts
      block:
        - name: Get instances facts
          amazon.aws.ec2_instance_info:
            region: "{{ region }}"
          register: result

        - name: Display Instance Details
          debug:
            msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
          loop: "{{ result.instances }}"

      tags: ['always']
